version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: articlesdb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./docker/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: articlesdb
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "3000:3000"
    depends_on:
      - db
